const CarData = [
  {
    id: 1,
    price: "1,500",
    Model: "Audi A1",
    Mark: "Audi",
    Year: "2012",
    Door: "4/5",
    AC: "Yes",
    Transmission: "Manual",
    Fuel: "Gasoline",
  },
  {
    id: 2,
    price: "1,200",
    Model: "Golf 6",
    Mark: "Volkswagen",
    Year: "2008",
    Door: "4/5",
    AC: "Yes",
    Transmission: "Manual",
    Fuel: "Diesel",
  },
  {
    id: 3,
    price: "1,000",
    Model: "Camry",
    Mark: "Toyota",
    Year: "2006",
    Door: "4/5",
    AC: "Yes",
    Transmission: "Automatic",
    Fuel: "Hybrid",
  },
  {
    id: 4,
    price: "1,300",
    Model: "320",
    Mark: "BMW",
    Year: "2012",
    Door: "4/5",
    AC: "Yes",
    Transmission: "Manual",
    Fuel: "Diesel",
  },
  {
    id: 5,
    price: "1,800",
    Model: "Benz GLK",
    Mark: "Mercedes",
    Year: "2006",
    Door: "4/5",
    AC: "Yes",
    Transmission: "Manual",
    Fuel: "Diesel",
  },
  {
    id: 6,
    price: "1,200",
    Model: "Passat CC",
    Mark: "Volkswagen",
    Year: "2008",
    Door: "4/5",
    AC: "Yes",
    Transmission: "Automatic",
    Fuel: "Gasoline",
  },
];
export default CarData;
